create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  birthdate date not null,
  zodiac text not null,
  zodiac_key text not null,
  zodiac_traits text not null,
  numbers int[] not null,
  bonus int not null,
  explanation text not null
);

alter table public.lotto_draws enable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant select, insert on public.lotto_draws to authenticated, service_role;
grant select on public.lotto_draws to anon;

drop policy if exists "service_role can manage lotto draws" on public.lotto_draws;
create policy "service_role can manage lotto draws"
on public.lotto_draws
for all
to service_role
using (true)
with check (true);

drop policy if exists "anon can read lotto draws" on public.lotto_draws;
create policy "anon can read lotto draws"
on public.lotto_draws
for select
to anon
using (true);
